import { MigrationInterface, QueryRunner } from "typeorm";

export class AddActorTypeToAuditLogs1772054021730 implements MigrationInterface {
    name = 'AddActorTypeToAuditLogs1772054021730'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "animal_types" DROP CONSTRAINT "FK_6e09189303eb07d5942f12b25b4"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP CONSTRAINT "FK_7d59a0ea2072d150bed1e5e24f4"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP CONSTRAINT "FK_f2878edd305475ce45bf307291c"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_55165766465bfd13d47adb4b2bd"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_113845d550b8ddafaabe3e1009f"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP CONSTRAINT "FK_34b511b460a2d2c1a728883ace1"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP CONSTRAINT "FK_988587d509b683ec72fca9f16fa"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_a94eeef88769d60a9ee08a02c40"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_e01b3eb43a6c8ae7d74d1ceeb2c"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_177183f29f438c488b5e8510cdb"`);
        await queryRunner.query(`ALTER TABLE "platform_user_roles" DROP CONSTRAINT "FK_be54b50127a06e3ecba31c81d4f"`);
        await queryRunner.query(`ALTER TABLE "platform_user_roles" DROP CONSTRAINT "FK_7ca5ece9c77acf7196c58a950b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7538058a66b2dff07496ed1192"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177183f29f438c488b5e8510cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0cbad1360aeda920c5aff6642"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e207a4390895169886b7b5a3"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "scheduled_at"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "species"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resource_type"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resource_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "clinic_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "changes"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "impersonation_context"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "client_ip"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "duration_ms"`);
        await queryRunner.query(`ALTER TABLE "animal_types" ADD "clinicId" uuid`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "reminder_id" uuid`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "direction" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "message_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "phone_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "messageBody" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "whatsapp_message_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "error_code" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "error_message" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "sent_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "read_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "clinicId" uuid`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "reminderId" uuid`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "clientId" uuid`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "pet_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "reminder_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "reminder_stage" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "scheduled_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "message_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "confirmed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "failed_reason" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "attempt_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "last_attempt_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "clinicId" uuid`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "petId" uuid`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "clientId" uuid`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "animal_type_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "birth_date" date`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "next_vaccine_date" date`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "next_deworming_date" date`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "clinicId" uuid`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "clientId" uuid`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "animalTypeId" integer`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "clinicId" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "actor_type" character varying(50) NOT NULL DEFAULT 'platform_user'`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "metadata" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09ed8fd739c3230357435ecee2"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "animal_types" DROP CONSTRAINT "PK_c4dd2b1389ccbade422c3d9a2f4"`);
        await queryRunner.query(`ALTER TABLE "animal_types" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "animal_types" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "animal_types" ADD CONSTRAINT "PK_c4dd2b1389ccbade422c3d9a2f4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "animal_types" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "animal_types" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "message_logs" ALTER COLUMN "status" SET DEFAULT 'delivered'`);
        await queryRunner.query(`ALTER TABLE "message_logs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reminders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "reminders" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reminders" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pets" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "plan" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "max_staff_users" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "max_clients" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "max_pets" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "active_staff_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "active_clients_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "active_pets_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d014f10f408c439d2e24c9c96f"`);
        await queryRunner.query(`ALTER TABLE "whatsapp_outbox" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "whatsapp_outbox" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "status" character varying(50) NOT NULL DEFAULT 'SUCCESS'`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_09ed8fd739c3230357435ecee2" ON "appointments" ("clinic_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f907efc568931b07c519d13bf" ON "message_logs" ("clinic_id", "whatsapp_message_id") WHERE direction = 'inbound'`);
        await queryRunner.query(`CREATE INDEX "IDX_7343e26eba496268b176ef7781" ON "message_logs" ("whatsapp_message_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_26433f0a692ca32c8728f30a14" ON "message_logs" ("direction", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2878edd305475ce45bf307291" ON "message_logs" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8fd5aee68088b344b84a789f61" ON "message_logs" ("reminder_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d59a0ea2072d150bed1e5e24f" ON "message_logs" ("clinic_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_113845d550b8ddafaabe3e1009" ON "reminders" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_161c6ae755fa6da1dd5fe5997f" ON "reminders" ("pet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f812386d7891859080ac8b422" ON "reminders" ("clinic_id", "scheduled_date", "status") WHERE status IN ('pending', 'sent')`);
        await queryRunner.query(`CREATE INDEX "IDX_3ca5cb9d497d50fd57c0823b5d" ON "reminders" ("clinic_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7538058a66b2dff07496ed1192" ON "whatsapp_outbox" ("idempotency_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_d014f10f408c439d2e24c9c96f" ON "whatsapp_outbox" ("clinic_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a85d553dbb4006bd350ab6f88" ON "audit_logs" ("actor_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_be54b50127a06e3ecba31c81d4" ON "platform_user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ca5ece9c77acf7196c58a950b" ON "platform_user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "animal_types" ADD CONSTRAINT "UQ_8424b00c85a792a67c33bec86ad" UNIQUE ("clinic_id", "name")`);
        await queryRunner.query(`ALTER TABLE "animal_types" ADD CONSTRAINT "FK_aee450f8ff49156982462351c75" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD CONSTRAINT "FK_7bd4265b2b34fbb569f29723838" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD CONSTRAINT "FK_9968383bfb30c272dd63cc27634" FOREIGN KEY ("reminderId") REFERENCES "reminders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD CONSTRAINT "FK_53329da1da55a94769838ac2264" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_de9a0806ba2607c7cbf61276320" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_af9e40623abbb83a7680f72eb09" FOREIGN KEY ("petId") REFERENCES "pets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_8ef092bfb710e607ece6c8a7e77" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pets" ADD CONSTRAINT "FK_bc5f4254afe221d0efd3e3bbe47" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pets" ADD CONSTRAINT "FK_ddeee2eea6e9192437a1bcf4632" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pets" ADD CONSTRAINT "FK_3632ba5cf4e90b060cbd50a5164" FOREIGN KEY ("animalTypeId") REFERENCES "animal_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_a7229d03a3d9a1107acb0fa4dde" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_user_roles" ADD CONSTRAINT "FK_be54b50127a06e3ecba31c81d4f" FOREIGN KEY ("user_id") REFERENCES "platform_users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "platform_user_roles" ADD CONSTRAINT "FK_7ca5ece9c77acf7196c58a950b0" FOREIGN KEY ("role_id") REFERENCES "platform_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "platform_user_roles" DROP CONSTRAINT "FK_7ca5ece9c77acf7196c58a950b0"`);
        await queryRunner.query(`ALTER TABLE "platform_user_roles" DROP CONSTRAINT "FK_be54b50127a06e3ecba31c81d4f"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_a7229d03a3d9a1107acb0fa4dde"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP CONSTRAINT "FK_3632ba5cf4e90b060cbd50a5164"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP CONSTRAINT "FK_ddeee2eea6e9192437a1bcf4632"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP CONSTRAINT "FK_bc5f4254afe221d0efd3e3bbe47"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_8ef092bfb710e607ece6c8a7e77"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_af9e40623abbb83a7680f72eb09"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_de9a0806ba2607c7cbf61276320"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP CONSTRAINT "FK_53329da1da55a94769838ac2264"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP CONSTRAINT "FK_9968383bfb30c272dd63cc27634"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP CONSTRAINT "FK_7bd4265b2b34fbb569f29723838"`);
        await queryRunner.query(`ALTER TABLE "animal_types" DROP CONSTRAINT "FK_aee450f8ff49156982462351c75"`);
        await queryRunner.query(`ALTER TABLE "animal_types" DROP CONSTRAINT "UQ_8424b00c85a792a67c33bec86ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ca5ece9c77acf7196c58a950b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be54b50127a06e3ecba31c81d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a85d553dbb4006bd350ab6f88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d014f10f408c439d2e24c9c96f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7538058a66b2dff07496ed1192"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ca5cb9d497d50fd57c0823b5d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f812386d7891859080ac8b422"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_161c6ae755fa6da1dd5fe5997f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_113845d550b8ddafaabe3e1009"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d59a0ea2072d150bed1e5e24f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fd5aee68088b344b84a789f61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2878edd305475ce45bf307291"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26433f0a692ca32c8728f30a14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7343e26eba496268b176ef7781"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f907efc568931b07c519d13bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09ed8fd739c3230357435ecee2"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "status" character varying(20) NOT NULL DEFAULT 'SUCCESS'`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(50) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`ALTER TABLE "platform_users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "platform_users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "platform_roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "whatsapp_outbox" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "whatsapp_outbox" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "IDX_d014f10f408c439d2e24c9c96f" ON "whatsapp_outbox" ("clinic_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "active_pets_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "active_clients_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "active_staff_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "max_pets" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "max_clients" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "max_staff_users" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clinics" ALTER COLUMN "plan" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pets" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reminders" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reminders" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reminders" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "message_logs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "message_logs" ALTER COLUMN "status" SET DEFAULT 'SENT'`);
        await queryRunner.query(`ALTER TABLE "animal_types" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "animal_types" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "animal_types" DROP CONSTRAINT "PK_c4dd2b1389ccbade422c3d9a2f4"`);
        await queryRunner.query(`ALTER TABLE "animal_types" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "animal_types" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "animal_types" ADD CONSTRAINT "PK_c4dd2b1389ccbade422c3d9a2f4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "IDX_09ed8fd739c3230357435ecee2" ON "appointments" ("clinic_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "actor_type"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "clinicId"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "animalTypeId"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "clientId"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "clinicId"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "next_deworming_date"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "next_vaccine_date"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "birth_date"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP COLUMN "animal_type_id"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "clientId"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "petId"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "clinicId"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "last_attempt_at"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "attempt_count"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "failed_reason"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "confirmed_at"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "message_id"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "scheduled_date"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "reminder_stage"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "reminder_type"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "pet_id"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "clientId"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "reminderId"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "clinicId"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "read_at"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "sent_at"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "error_message"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "error_code"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "whatsapp_message_id"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "messageBody"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "message_type"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "direction"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP COLUMN "reminder_id"`);
        await queryRunner.query(`ALTER TABLE "animal_types" DROP COLUMN "clinicId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "duration_ms" integer`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "client_ip" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "impersonation_context" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "changes" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "clinic_id" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resource_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resource_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "date_of_birth" date`);
        await queryRunner.query(`ALTER TABLE "pets" ADD "species" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "scheduled_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "message" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD "message" text NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_99e207a4390895169886b7b5a3" ON "audit_logs" ("clinic_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0cbad1360aeda920c5aff6642" ON "audit_logs" ("resource_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_177183f29f438c488b5e8510cd" ON "audit_logs" ("actor_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7538058a66b2dff07496ed1192" ON "whatsapp_outbox" ("idempotency_key") `);
        await queryRunner.query(`ALTER TABLE "platform_user_roles" ADD CONSTRAINT "FK_7ca5ece9c77acf7196c58a950b0" FOREIGN KEY ("role_id") REFERENCES "platform_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_user_roles" ADD CONSTRAINT "FK_be54b50127a06e3ecba31c81d4f" FOREIGN KEY ("user_id") REFERENCES "platform_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_177183f29f438c488b5e8510cdb" FOREIGN KEY ("actor_id") REFERENCES "platform_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_e01b3eb43a6c8ae7d74d1ceeb2c" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_a94eeef88769d60a9ee08a02c40" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pets" ADD CONSTRAINT "FK_988587d509b683ec72fca9f16fa" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pets" ADD CONSTRAINT "FK_34b511b460a2d2c1a728883ace1" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_113845d550b8ddafaabe3e1009f" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_55165766465bfd13d47adb4b2bd" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD CONSTRAINT "FK_f2878edd305475ce45bf307291c" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD CONSTRAINT "FK_7d59a0ea2072d150bed1e5e24f4" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "animal_types" ADD CONSTRAINT "FK_6e09189303eb07d5942f12b25b4" FOREIGN KEY ("clinic_id") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
